### ISSUE TITLE
switchPlayer(); function not running after random move

### ISSUE THREAD

**Issue by rachelhamlin** [rachelhamlin/TicTacToe#3]
I use the function switchPlayer(); to highlight the current player for the user. In the two player version of my game, switchPlayer(); runs every time a square is clicked to switch back and forth.

In the computer version, switchPlayer(); is supposed to run both after the player clicks, and after the computer makes a random move (in randomizeMove();). But the randomizeMove(); function is returning an error: "this.switchPlayer() is not a function." 

The switchPlayer function: 
`tictactoeGame.switchPlayer = function () {  // this highlights the active player on the page (for the user to keep track)
  if (gameWon == true) {
    return;
  } else {
    $('.one').toggleClass('active');
    $('.two').toggleClass('active');
  }
};`

The randomizeMove function: 
`tictactoeGame.randomizeMove = function () {   // this generates a move for the computer after the player makes a move
  var emptySquares = $('.square').not('.marked').length;
  var randomNum = Math.floor(Math.random () * emptySquares);
  var randomSquare = $('.square').not('.marked').eq(randomNum);
  if ( (gameWon == false) && (playerOneTurn == false) ) {
    randomSquare.text('O').addClass('marked o');
    turn++;
    playerOneTurn = true;
    this.switchPlayer();
  }
};`

**Comment by carrafa** [comment]
_met in person_
